### ISSUE TITLE
no way to know who's turn it is

### ISSUE THREAD

**Issue by porterjamesj** [millerjs/quoridor#3]
and even if this were implemented, the client would have to hammer the server with long polling in order to have the most time to make it's turn

the way i've seen this done in the past is that the players are webservers also, and they "register" with the game server by sending it a callback url, which the game server sends a request to every time it's their turn, expecting to recieve a response representing the player's move. the game server is responsible for randomly setting up matches between all the registered players and just keeps running matches and saving the results

**Comment by millerjs** [comment]
Addressed by `/wait_for_activity`
